[package]
name = "yapl"
version = "0.3.0"
authors = ["Konosuke Kachi <github@s.k-kachi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8"
rand = "0.7"
